"""empty message

Revision ID: 74a254656028
Revises: 2369deb8ecd4
Create Date: 2021-09-02 04:53:08.125352

"""
from alembic import op
import fastapi_utils.guid_type 
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a254656028'
down_revision = '2369deb8ecd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
