"""update user column again

Revision ID: 7df6ce9d1f24
Revises: d2295f928a6b
Create Date: 2020-10-13 13:33:08.546460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df6ce9d1f24'
down_revision = 'd2295f928a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bussines_type', sa.String(), nullable=True))
    op.drop_column('users', 'bussiner_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bussiner_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'bussines_type')
    # ### end Alembic commands ###
