"""alter auth token

Revision ID: 92ff36aa91c9
Revises: 625891c5a038
Create Date: 2020-10-13 14:53:46.994129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ff36aa91c9'
down_revision = '625891c5a038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_token', sa.Column('expired_at', sa.DateTime(), nullable=True))
    op.drop_column('auth_token', 'token_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_token', sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('auth_token', 'expired_at')
    # ### end Alembic commands ###
