"""update user column

Revision ID: d2295f928a6b
Revises: ea10dd8ecf42
Create Date: 2020-10-13 13:32:06.710395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2295f928a6b'
down_revision = 'ea10dd8ecf42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
