"""empty message

Revision ID: eb3d323ad011
Revises: d630349bb58b
Create Date: 2021-09-02 04:47:20.862461

"""
from alembic import op
import fastapi_utils.guid_type 
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3d323ad011'
down_revision = 'd630349bb58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
