"""empty message

Revision ID: ed025af8ce6b
Revises: 3a48579973f0
Create Date: 2021-09-01 01:57:36.184497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed025af8ce6b'
down_revision = '3a48579973f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
