"""empty message

Revision ID: f945bb4c7f16
Revises: 48559ed9169c
Create Date: 2021-09-02 04:50:56.645201

"""
from alembic import op
import fastapi_utils.guid_type 
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f945bb4c7f16'
down_revision = '48559ed9169c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
